### ISSUE TITLE
Remove Bogus Link in README

### ISSUE THREAD

**Issue by jetsgit** [yeoman/generator-angular#1360]
At the top of the README there is a link,

[this comparison](http://www.dancancro.com/comparison-of-angularjs-application-starters)

which is a link to a Dan Cancro page that is not accessible. This is bogus, could it be removed? 

Evidently it is necessary to request access from Dan in order to view the document.  Just seems like way to many hoops to jump thru to get some documentation. Could this be accessed in another fashion, or just pruned out since currently seems like a waste of time?

It seems Dan has some type of agenda going on that does not appear to be  in the spirit of open source. I am not only person flustered. Here is a comment from that page:

> Evin C
> Dan – I see that you’ve made the doc inaccessible unless a user has been granted access, and it seems from what you’re saying that you need to contribute knowledge in order to get access? Is that right?
> If so – that seems slightly counter intuitive for a comparison doc meant for beginners to get involved in the process and to learn the components that each of the generators offer.
> I can see making something like that working better in an expert community, but I don’t think that’s your user-base here. Even then – the web is all about open content, not forcing people to contribute in order to benefit. Open source works because people WANT to contribute, not because they’re forced to. The maintainer of that is the one allowing or disallowing changes. Currently that’s you, but I’m sure you could hand that responsibility to a trusted individual if you wanted.

I just feel this approach is not egalitarian. If Dan could open access up I would not have a problem, but currently it does not feel quite so open in regard to access, and it does not seem like such a good association for Yeoman.

**Comment by dancancro** [comment]
Hi Jerry,

I definitely see what you mean. I think the link should be removed too. Here's the story behind it.

I'm a beginner and made this for beginners because of the acute pain of option overload and wasted research time that I experienced, but without help I don't have the time or altruism to collect all the information myself, especially when people using and familiar with each technology (there are now 500+ interdependent technologies in the database) could collectively do it so much faster than I could.  That was an expectation of open source community that I miscalculated. I could have asked for money but figured that was contrary to the spirit. 

Unfortunately, few people with the answers have been moved to enter them. They're busy but more importantly they don't want to expose their beloved technologies to head-to-head comparisons that could possibly misrepresent them, or represent them, but not favorably.  I asked for help from every expert I could reach until I decided that it wasn't worth it anymore.

There is a ton of constantly changing data to collect and likewise a ton of decision anguish and buyer's remorse to help people avoid. I still record useful facts one by one as I learn them and I will keep trying to think of a way to make data collection sustainable. I'm open to ideas. But so far nothing has worked.  The most recent idea was to ask beginners to lobby experts for their participation individually in exchange for access. When nobody took me up on that offer, I concluded that people didn't want it bad enough for me to keep at it full time. I've been unemployed for 13 years. So it's tough for me to help save well paid engineers massive amounts of time without their willingness to give back to the community by answering a few easy questions or sending an email. I hope you can see my position.

If you haven't already, check out [Stackshare](http://stackshare.io/stackups). It has a much bigger set of data than mine. It's mostly opinion data and doesn't do aggregate benefit comparisons like [my one](http://dancancro.com/meanio_vs_meanjs.html), but it's pretty cool.

**Comment by eddiemonge** [comment]
removed in https://github.com/yeoman/generator-angular/commit/0ceb6a22487df0bb89b2400f23166aa33836dde7#diff-0730bb7c2e8f9ea2438b52e419dd86c9
