### ISSUE TITLE
generate routes using ui-router instead of generic Angular router

### ISSUE THREAD

**Issue by patcito** [yeoman/generator-angular#305]
Would be great to have an option to generate routes using ui-router instead from https://github.com/angular-ui/ui-router

**Comment by lobo-tuerto** [comment]
Maybe now is a good time to revisit this issue?

Would love to see ui.router considered as an option in the generator.

**Comment by johnhoffman** [comment]
+1

My projects generally always require nested views! :)

**Comment by tritonresearch** [comment]
+1

**Comment by brunowego** [comment]
+1

**Comment by crowne** [comment]
+1

**Comment by DavidBrower** [comment]
It would be great to see a Angular generator with the ui-router.

**Comment by geoguide** [comment]
+1, though it looks like this will probably do it? https://www.npmjs.com/package/generator-angular-ui-router

**Comment by Kotzilla** [comment]
+1

**Comment by vikrant2mahajan** [comment]
+1

**Comment by marcoamtz** [comment]
+1

**Comment by HieuMinhHoang** [comment]
+1

**Comment by victorkohl** [comment]
+1

**Comment by eugenehp** [comment]
:+1:

**Comment by yogieputra8** [comment]
+1

**Comment by annakaringal** [comment]
+1

**Comment by ayman-alkom** [comment]
+1

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] generate routes using ui-router instead of generic
Angular router (#305)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by stuarthallows** [comment]
+1

**Comment by jwhitmarsh** [comment]
:+1:

**Comment by askie** [comment]
+1

**Comment by yohendry** [comment]
+1

**Comment by alexisllamas** [comment]
+1

**Comment by xals** [comment]
+1 https://www.npmjs.com/package/generator-angular-ui-router seems not maintained. And it is unable to properly add a route in $stateProvider.

**Comment by Miguelme** [comment]
+1

**Comment by redfox05** [comment]
+1 this has been requested for years, as can be seen by the comments. Can this be reconsidered?
Or, can someone suggest how best to modify the outputted yeoman scaffold. Is it as simple as just editing the dependancies and writing the new code? That's what we did, but is that the best way? You'd then you lose the ability to use the nice yeoman features to add new routes. Correct?

**Comment by Nadejde** [comment]
+1

**Comment by denisazevedo** [comment]
+1

**Comment by abielikesu** [comment]
+1

**Comment by jeffersonsouza** [comment]
+1

**Comment by asartz** [comment]
+1

**Comment by sickrandir** [comment]
+1

**Comment by cidus** [comment]
+1

**Comment by irwebuniq** [comment]
+1

**Comment by mostafabarmshory** [comment]
+1

**Comment by bwynne** [comment]
+1

**Comment by ksgupta** [comment]
+1. Is this part of any milestone already?

**Comment by SeraphicScribe** [comment]
+1. Any updates in this regard?

**Comment by nomah82** [comment]
+1

**Comment by ishanthilina** [comment]
+1
