### ISSUE TITLE
Broken relative URLs to Bootstrap glyphicons in vanilla app (without sass)

### ISSUE THREAD

**Issue by shmert** [yeoman/generator-angular#645]
I created a brand new yeoman app:
    % yo angular:app
    [?] Would you like to use Sass (with Compass)? No
    [?] Would you like to include Bootstrap? Yes

Then I ran
    % grunt build

The resulting build puts the bootstrap css into styles/cd367326.vendor.css

This bootstrap has an absolute reference to the glyphicons at `/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot`

This URL breaks with a 404 if the project is hosted in a subdirectory on the web server.

**Comment by superghostmaster** [comment]
This issue is still prevalent in the current generator among a LOT of file paths.

This is amateur hour.  This is the kind of thing that should be found before a version deployment.

For those looking for a Yeoman-based generator that actually works correctly, follow the (slightly outdated) guide over @ Meanjs.org.

**Comment by eddiemonge** [comment]
@superghostmaster please open an issue if you believe this is the case but I haven't seen anything wrong related to paths.

**Comment by rjw57** [comment]
@eddiemonge was that #978? (For those following this issue.)
