### ISSUE TITLE
Generator stucks after angular-scenario

### ISSUE THREAD

**Issue by RyanAntenor** [yeoman/generator-angular#775]
At installation it stucks after this: 

...
json3#3.3.2 bower_components/json3
es5-shim#3.1.1 bower_components/es5-shim
angular-mocks#1.2.16 bower_components/angular-mocks
└── angular#1.2.16
angular-scenario#1.2.16 bower_components/angular-scenario
└── angular#1.2.16

**Comment by computersarecool** [comment]
I am trying to use the angular generator with the [yeoman codelab] (http://yeoman.io/codelab/) It is currently hanging here:

jquery#2.1.3 bower_components/jquery

I have the following installed on my machine (a Mac running 10.10.1)

npm -v 2.1.18
node -v v0.10.35
bower -v 1.3.12
grunt-cli v0.1.13
grunt v0.4.5
git v1.9

Nothing happens when running yo-angular after that point. Pressing enter just exits the generator.

**Comment by eddiemonge** [comment]
@computersarecool you have a ton of npm errors. try running `npm cache clean` and then try again

**Comment by computersarecool** [comment]
Nice! Thanks for the help. Works great.
