### ISSUE TITLE
Generator with ionic framework

### ISSUE THREAD

**Issue by nschurmann** [yeoman/generator-angular#984]
Anyone have experience configuring this generator with ionic framework?

**Comment by OminStyle** [comment]
I combined Yeoman angular generator with ionic-cli so that I can benefit from both. I use yo angular commands to generate the boilerplates and when I feel that I need to test the cordova app on a mobile device, I build with ionic commands. Have a look if you're interested. https://github.com/OminStyle/yo-angular-ionic-cli

**Comment by nschurmann** [comment]
Thanks!, i will dig into this!
