### ISSUE TITLE
Send input while redirecting output makes the generator hang

### ISSUE THREAD

**Issue by Colin-Murphy** [yeoman/generator-angular#999]
I need to call this generator via python in a webapp I've been working on. Originally I did this by piping yes to the generator but I need to say no to the first option.

    yes | yo angular --no-insight

 Now I am sending the output of a file to the generator to tell it to enter

    cat input.txt | yo angular --no-insight

input.txt

    n
    y
    y

This works just fine, but I also need to store the logs so I redirect the output to out.txt 

    cat input.txt | yo angular --no-insight > out.txt

This is where things go wrong, the first prompt is answered with a no as I would expect, then everything just stops.

I need a way to programatically run the generator, I thought that using an Adaptor would be the solution, but there seems to be absolutely no documentation for writing one.

What should I do to fit my use case?

**Comment by eddiemonge** [comment]
this is where having this as a composable generator comes into play. until then i dont think you can do this. im amazed that the piping part worked. @SBoudrias might have ideas though

**Comment by SBoudrias** [comment]
Inquirer being async, I guess it makes sense piping the text file might be flakey (maybe the pipe send the keys too fast). I must say I'm pretty amazed this worked before you pipe the output.

Maybe the solution would be to ask the generator to provide command line flag/options to optionally replace prompts. This would be the easiest solution. Otherwise you could use an Adapter, but that seems like a lot of work... If you want to explore this option, just check the TerminalAdapter and yo implementation (basically you should drop yo and use your own tool for running Yeoman generators with a custom adapter). There's no written documentation about this yet, so it's really reading yo code and https://github.com/yeoman/environment

**Comment by eddiemonge** [comment]
closing this issue as it isnt documented that it will work. It might in the future when most/all options are command line flags (which is a goal).
